import { GenElement } from './Element';

export const LOGOCONTENT: GenElement[] = [
  {
    id: 1,
    type: 2,
    position: 1,
    height: 117,
    width: 951,
    top: -27,
    left: -14,
    src: './assets/banner1/top.png',
  },
  {
    id: 2,
    type: 2,
    position: 2,
    height: 208,
    width: 714,
    top: 490,
    left: -73,
    src: './assets/banner1/bottom.png',
  },
  {
    id: 3,
    type: 2,
    position: 3,
    height: 208,
    width: 714,
    top: 490,
    left: 268,
    src: './assets/banner1/bottom.png',
  },
  {
    id: 4,
    type: 2,
    position: 4,
    height: 270,
    width: 223,
    top: 144,
    left: 35,
    src: './assets/banner1/sushil.png',
  },
  {
    id: 5,
    type: 2,
    position: 5,
    height: 270,
    width: 223,
    top: 144,
    left: 683,
    src: './assets/banner1/asbin.png',
  },
  {
    id: 6,
    type: 2,
    position: 6,
    height: 132,
    width: 132,
    top: 116,
    left: 399,
    src: './assets/banner1/logo.png',
  },
  {
    id: 7,
    type: 3,
    position: 7,
    top: 297,
    left: 280,
    text: 'LEO CLUB OF KATHMANDU',
    fontColor: '#CE3C3F',
    fontFamily: 9,
    fontSize: 28.42,
    fontWeight: 'bold',
    bold: true,
    italic: false,
    underline: false,
  },
  {
    id: 8,
    type: 3,
    position: 8,
    top: 331,
    left: 399,
    text: 'RESUNGA',
    fontColor: '#CE3C3F',
    fontFamily: 9,
    fontSize: 28.42,
    fontWeight: 'bold',
    bold: true,
    italic: false,
    underline: false,
  },
  {
    id: 9,
    type: 3,
    position: 9,
    top: 392,
    left: 371,
    text: 'Produdly presents',
    fontColor: 'black',
    fontFamily: 10,
    fontSize: 28.42,
    fontWeight: 'bold',
    bold: true,
    italic: false,
    underline: false,
  },
  {
    id: 10,
    type: 3,
    position: 10,
    top: 441,
    left: 34,
    text: 'LEO SUSHIL BHANDARI',
    fontColor: '#184F96',
    fontFamily: 2,
    fontSize: 22.5,
    fontWeight: 'bold',
    bold: true,
    italic: false,
    underline: false,
  },
  {
    id: 11,
    type: 3,
    position: 11,
    top: 474,
    left: 52,
    text: 'District President Candidate',
    fontColor: '#7E7377',
    fontFamily: 2,
    fontSize: 15,
    fontWeight: 'bold',
    bold: true,
    italic: false,
    underline: false,
  },
  {
    id: 12,
    type: 3,
    position: 12,
    top: 441,
    left: 665,
    text: 'LEO ASHWIN KHATIWADA',
    fontColor: '#184F96',
    fontFamily: 2,
    fontSize: 22.5,
    fontWeight: 'bold',
    bold: true,
    italic: false,
    underline: false,
  },
  {
    id: 13,
    type: 3,
    position: 13,
    top: 474,
    left: 683,
    text: 'District Vice-President Candidate',
    fontColor: '#7E7377',
    fontFamily: 2,
    fontSize: 15,
    fontWeight: 'bold',
    bold: true,
    italic: false,
    underline: false,
  },
  {
    id: 14,
    type: 3,
    position: 14,
    top: 444,
    left: 385,
    text: 'L. Y. 2022/2023',
    fontColor: '#2657A0',
    fontFamily: 2,
    fontSize: 23,
    fontWeight: 'bold',
    bold: false,
    italic: true,
    underline: false,
  },
  {
    id: 15,
    type: 3,
    position: 15,
    top: 478,
    left: 451,
    text: 'FOR',
    fontColor: 'black',
    fontFamily: 9,
    fontSize: 12,
    fontWeight: 'bold',
    bold: true,
    italic: false,
    underline: false,
  },

  {
    id: 16,
    type: 3,
    position: 16,
    top: 503,
    left: 315,
    text: 'Leo District Council 325 M, Nepal',
    fontColor: '#D25E46',
    fontFamily: 2,
    fontSize: 21,
    fontWeight: 'bold',
    bold: false,
    italic: false,
    underline: false,
  },
  {
    id: 17,
    type: 3,
    position: 17,
    top: 539,
    left: 315,
    text: '100%  YES VOTE',
    fontColor: '#2657A0',
    fontFamily: 9,
    fontSize: 38,
    fontWeight: 'bold',
    bold: true,
    italic: false,
    underline: false,
  },
];
